name: ol-rl
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up mingw
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: any
      - name: build ol-rl.exe
        shell: bash
        run: make ol-rl.exe
      - name: Set commit based variables
        shell: bash
        run: |
          echo "FINAL_FILE_NAME=ol-rl-$(git rev-parse --short "$GITHUB_SHA").exe" >> "$GITHUB_ENV"
      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FINAL_FILE_NAME }}
          path: ol-rl.exe
